### PR TITLE
Meetup blog

### PR DESCRIPTION
**Pull request by suppathak**
Added blog post for meetup 1, 2, and 3.

### CODE REVIEW

**Comment by suppathak** [comment]
> Could you please also add headings, dates, and speaker names(the presenter mainly) to this as well?

@aakankshaduggal, I have made changes as per your feedback. Please have a look and let me know if I need to add anything. Thanks :)

**Review by aakankshaduggal — COMMENTED** [review]
thanks @suppathak 
/lgtm :)

**Review by aakankshaduggal — APPROVED** [review]
/approve

**Pull request merged**
